### PR TITLE
License as MIT license

### PR DESCRIPTION
**Pull request by puiterwijk**
Needs approval from all current contributors.

For all contributors, please add a comment stating you agree to this project being under the MIT license.
Current contributors per git:
- [x] @puiterwijk
- [x] @kittykat 
- [x] @andreasn 
- [x] @benzea 
- [x] @stickster 
- [x] @robyduck
- [x] @jwboyer

### CODE REVIEW

**Comment by puiterwijk** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

**Comment by andreasn** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

**Comment by kittykat** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

**Comment by stickster** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

**Comment by robyduck** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

**Comment by jwboyer** [comment]
I agree to licensing this code under the MIT license as specified in COPYING.

(Though the pull request is confusing because it says under the FPCA.)

**Comment by puiterwijk** [comment]
@jwboyer you are correct, I am sorry, and have corrected this. The rest of the text and license are still the same.

**Comment by puiterwijk** [comment]
Since we now have approval from all current contributors to the best of my knowledge, I am merging this PR.
Thanks everyone for your help on this matter.

**Pull request merged**
