### PR TITLE
Drop OpenID 2.0 and make OpenIDC return url provider-specific

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by ghost** [comment]
This would mean we can't use the master branch for http://registration.guadec.org/ any more. The only OpenIDC connect provider we have set up is Google and I am definitely not going to require everyone to have a Google account.

We could make a branch for registration.guadec.org though.

**Comment by puiterwijk** [comment]
@ssssam Both GNOME and Fedora are OpenID Connect providers as well, so you could use that.

**Comment by puiterwijk** [comment]
e.g.: https://id.fedoraproject.org/openidc/.well-known/openid-configuration

**Comment by ghost** [comment]
Good point! I forgot that id.gnome.org had been upgraded.  OK, fine by me then.

**Comment by puiterwijk** [comment]
Thanks. I'll make sure to set up OpenIDC for GNOME and Fedora before we push this to master.

**Pull request merged**
