### PR TITLE
test/registration: Test shouldn't fail if Inkscape is missing

### PR DESCRIPTION
**Pull request by ghost**
The badge-printing functionality requires Inkscape to be installed. This
isn't installed by default in many distros so we should handle the case
where it's missing. Now the test in question will be skipped if Inkscape
isn't available.

### CODE REVIEW

**Comment by puiterwijk** [comment]
It would be great if you could add inkscape to the travis config file, so that the travis tests still check this code.

**Comment by ghost** [comment]
inkscape is already in the config file, the travis tests wouldn't ever have worked otherwise. However, obviously I something wrong since the tests that require inkscape no longer run. I'll investigate.

**Comment by ghost** [comment]
The problem appears to be that I used the child_process.execSync() function, but that's not present in Node 0.10. Since we choose to use 0.10 in travis.yml. Fix depends on whether we still need to support Node 0.10 or not.

**Comment by ghost** [comment]
This should be ready to merge now, no more loss in test coverage

**Comment by ghost** [comment]
Actually, the last version was totally broken too. Am still getting used to this "asynchronous by default" business of Node.js..

**Comment by ghost** [comment]
OK, this seems to once again work locally (without Inkscape) and in Travis. Sorry for all the noise!

**Pull request merged**
